apiVersion: v2
name: swisspine_chart
version: 0.0.1
appVersion: 0.0.1
description: "SwissPine"

dependencies:
  # Ingress Controller
  - name: ingress-nginx
    repository: https://kubernetes.github.io/ingress-nginx
    version: 4.7.0
