apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    name: {{ .Values.service.name }}
    app: {{ .Values.service.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port}}
      targetPort: {{ .Values.deployment.container_port }}